# Server configuration
server:
  port: 8081
  servlet:
    context-path: /

# Trino connection properties
trino:
  host: localhost
  port: 8080
  user: trino
  catalog: iceberg
  schema: default

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
  packages-to-scan: com.gs.datalakehouse.api.controller
  show-actuator: false
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
